#!/bin/bash

# Copyright (c) Winton. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENCE in the project root for license information.

set -euo pipefail

# Script to generate the Version.targets file in the root of the working tree

case "$#" in
    1)
        commitish="$1";
    ;;
    0)
        commitish=""
    ;;
    *)
        echo "Usage: $0 [<commit-ish>]";
        exit 1;
esac;

# Get where this script is (thanks StackOverflow! http://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within)
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
version_targets=$script_dir/../../Version.targets

file_version=$($script_dir/calculate_file_version.sh $commitish)
echo "File version  : $file_version"
assembly_version=$($script_dir/calculate_assembly_version.sh $commitish)
echo "Assembly version: $assembly_version"
version_prefix=${file_version%%-*}
echo "Version prefix  : $version_prefix"
version_suffix=${file_version#*-}
echo "Version suffix  : $version_suffix"

cat > $version_targets <<EOF
<!--
THIS FILE IS AUTO-GENERATED BY TOOL AND COULD BE OVERWRITTEN AT ANY TIME.
-->
<Project>
    <PropertyGroup>
        <AssemblyVersion>$assembly_version</AssemblyVersion>
        <VersionPrefix>$version_prefix</VersionPrefix>
        <VersionSuffix>$version_suffix</VersionSuffix>
        <GenerateAssemblyVersionAttribute>true</GenerateAssemblyVersionAttribute>
    </PropertyGroup>
</Project>
EOF
