name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Version
      if: ${{ github.event_name != 'pull_request' }} 
      run: etc/scripts/write_version_targets.sh
      shell: bash
    - name: Restore dependencies
      run: >
        dotnet restore
    - name: Build
      run: >
        dotnet build
        --no-restore --configuration Release --framework netstandard2.0
        Winton.Extensions.Threading.Actor/Winton.Extensions.Threading.Actor.csproj
    - name: Test
      run: >
        dotnet test
        --no-restore --verbosity normal --configuration Release --framework net5.0
        Winton.Extensions.Threading.Actor.Tests.Unit/Winton.Extensions.Threading.Actor.Tests.Unit.csproj
    - name: Pack
      if: ${{ startsWith(matrix.os, 'windows-') }} 
      run: >
        dotnet pack
        --no-build --no-restore --configuration Release --output .
        Winton.Extensions.Threading.Actor/Winton.Extensions.Threading.Actor.csproj
    - name: Push
      if: ${{ startsWith(matrix.os, 'windows-') && github.event_name == 'release' }} 
      run: >
        dotnet nuget push
        *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
